services:
  web:
    depends_on:
      - api
    container_name: web
    build:
      context: .
      dockerfile: ./src/apps/web/Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: api
  api:
    container_name: api
    depends_on:
      - qdrant
      - embeddings
    build:
      context: .
      dockerfile: ./src/apps/api/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      SERVER_PORT: 3001
      SERVER_HOST: 0.0.0.0
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      EMBEDDINGS_HOST: embeddings
      EMBEDDINGS_PORT: 80
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  embeddings:
    container_name: embeddings
    image: michaelf34/infinity:0.0.75
    ports:
      - "8081:7997"
    environment:
      INFINITY_MODEL_ID: ${MODEL_ID:-"sentence-transformers/all-MiniLM-L6-v2"}
    command: v2
volumes:
  qdrant_data: