packages:
  - src/apps/*
  - src/packages/*
  - src/dev/*
autoInstallPeers: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - normalize-diacritics
  - onnxruntime-node
  - protobufjs
  - sharp
strictPeerDependencies: true
