#$schema:https://render.com/schema/render.yaml.json
version: "1"
services:
  - type: web
    name: map-of-science
    runtime: static
    repo: https://github.com/wujekbogdan/map-of-science
    branch: main
    buildCommand: pnpm i --frozen-lockfile && pnpm turbo build --filter=@map-of-science/web
    staticPublishPath: ./src/apps/web/dist/
    envVars:
      - fromGroup: prod
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeployTrigger: off
    previews:
      generation: off
  - type: web
    name: map-of-science-api
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: ghcr.io/wujekbogdan/map-of-science-api-server:stable
    envVars:
      - fromGroup: prod
    healthCheckPath: /health
    previews:
      generation: off
