name: Check for Changesets

on:
  pull_request:
    branches:
      - main

jobs:
  check-for-changeset:
    runs-on: ubuntu-24.04
    steps:
      - uses: dorny/paths-filter@v3
        id: changeset
        with:
          filters: |
            changeset:
              - '.changeset/*.md'

      - name: Fail if no changeset
        if: steps.changeset.outputs.changeset != 'true' && github.actor != 'github-actions[bot]'
        run: |
          echo "❌ No changeset found!"
          exit 1